import { randomBytes, createCipheriv, createDecipheriv } from "node:crypto";

// Application-level encryption for personnel PII (SSN, driver's license
// number) that must be encrypted at rest but has nowhere safe to be
// encrypted in a portable SQL migration - see the note on
// Personnel.ssnEncrypted in schema.prisma for why those two columns are
// nullable at the DB level even though the rest of this pass tightened
// everything else to NOT NULL.
//
// AES-256-GCM, not a Postgres extension (e.g. pgcrypto): keeping
// encryption in application code means every write still goes through
// Prisma's normal typed client - no raw SQL, no risk of the plaintext or
// the key ever appearing in a query the database logs. It also means this
// module is plain, dependency-free TypeScript, testable without a
// database, matching the rest of this codebase's pure-logic-in-its-own-
// file convention (money.ts, craft.ts, employeeId.ts).
//
// Storage format for one encrypted value, as a single Buffer:
//   [12-byte IV][16-byte GCM auth tag][ciphertext]
// The IV is random per encryption (required for GCM - reusing an IV with
// the same key breaks its confidentiality guarantee), so encrypting the
// same plaintext twice produces different bytes each time. The auth tag
// means a single flipped bit anywhere in storage makes decryption throw
// rather than silently return corrupted data.

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12; // 96 bits - the length GCM is designed for
const AUTH_TAG_LENGTH = 16;
const KEY_LENGTH = 32; // AES-256

export class PiiEncryptionKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PiiEncryptionKeyError";
  }
}

// Reads and validates the key on every call rather than caching it at
// module load - this module is imported by places (like tests) that
// deliberately run without the env var set, and failing at the point of
// use gives a clearer error than a cached `undefined` would.
function loadKey(): Buffer {
  const raw = process.env.PII_ENCRYPTION_KEY;
  if (!raw) {
    throw new PiiEncryptionKeyError(
      "PII_ENCRYPTION_KEY is not set. Generate one with " +
        "`openssl rand -base64 32` and set it in .env before storing or " +
        "reading any personnel SSN or driver's license number."
    );
  }

  let key: Buffer;
  try {
    key = Buffer.from(raw, "base64");
  } catch {
    throw new PiiEncryptionKeyError("PII_ENCRYPTION_KEY is not valid base64.");
  }

  if (key.length !== KEY_LENGTH) {
    throw new PiiEncryptionKeyError(
      `PII_ENCRYPTION_KEY must decode to exactly ${KEY_LENGTH} bytes (got ${key.length}). ` +
        "Generate one with `openssl rand -base64 32`."
    );
  }

  return key;
}

// Returns a plain Uint8Array backed by its own ArrayBuffer, not a Node
// Buffer - Prisma's generated types for a Bytes column want exactly that
// (Uint8Array<ArrayBuffer>), and a Buffer's backing store is typed as the
// more general ArrayBufferLike, which does not satisfy it. Buffer is used
// internally for the concat/crypto work; only the return value is
// converted.
// The return type is explicitly Uint8Array<ArrayBuffer>, not the bare
// (wider) Uint8Array a plain annotation would default to - Prisma's
// generated Bytes-column type wants exactly this narrower form, and an
// unparameterized Uint8Array return annotation discards the narrower type
// the function body actually produces.
export function encryptPii(plaintext: string): Uint8Array<ArrayBuffer> {
  const key = loadKey();
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv);

  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  const combined = Buffer.concat([iv, authTag, ciphertext]);

  // `new Uint8Array(length)` is the one construction TypeScript's lib types
  // guarantee is backed by a real ArrayBuffer rather than the more general
  // ArrayBufferLike (which also covers SharedArrayBuffer) that a Buffer -
  // or Uint8Array.from(buffer) - carries. Prisma's generated type for a
  // Bytes column specifically wants Uint8Array<ArrayBuffer>.
  const result = new Uint8Array(combined.length);
  result.set(combined);
  return result;
}

// Throws if the key is wrong or the stored bytes have been altered -
// GCM's authentication check fails closed rather than returning garbage
// that looks like a plausible SSN.
//
// Takes a Uint8Array, not a Buffer: that is what Prisma hands back when
// reading a Bytes column, and encryptPii's output is typed the same way
// for the matching reason.
export function decryptPii(stored: Uint8Array): string {
  const key = loadKey();

  if (stored.length < IV_LENGTH + AUTH_TAG_LENGTH) {
    throw new Error("Stored PII value is too short to contain an IV and auth tag");
  }

  const iv = stored.subarray(0, IV_LENGTH);
  const authTag = stored.subarray(IV_LENGTH, IV_LENGTH + AUTH_TAG_LENGTH);
  const ciphertext = stored.subarray(IV_LENGTH + AUTH_TAG_LENGTH);

  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);

  return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
}

// Renders only the last `visibleDigits` characters, for a detail page that
// needs to show "on file, ending in 6789" without ever decrypting the
// full value into a page render. Takes the plaintext (called right after
// decryptPii, in the same server-side scope) rather than the Buffer,
// since masking is about what gets displayed, not how it was stored.
export function maskKeepingLast(plaintext: string, visibleDigits = 4): string {
  const visible = plaintext.slice(-visibleDigits);
  return `••••${visible}`;
}
